# Generated by Django 5.1.6 on 2025-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='full_text',
            field=models.TextField(default='No content', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='articles',
            name='intro',
            field=models.CharField(default='No introduction', max_length=250, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default='Untitled', max_length=50, verbose_name='Title'),
        ),
    ]
